name: CI-Pipelines

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: jkcuenca20/devopsPipelines/.github/workflows/main.yml@main
    with:
      docker_image_name: hola-mundo-clase123
    secrets: inherit